# vim:ff=unix:ts=2:sw=2:ai:expandtab
---
version: '3.7'
services:
  daemon:
    build:
      context: daemon/
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
    volumes:
      - daemon:/var/lib/transmission
      - /srv/library:/var/lib/transmission/downloads
    restart: always
    networks:
      default:
        aliases:
          - transmission-daemon

  rss:
    build:
      context: rss/
    volumes:
      - rss:/var/lib/transmission-rss/
    restart: always

  ftp:
    build:
      context: vsftpd/
    volumes:
      - /srv/library:/var/lib/transmission/downloads
    ports:
      - '21:21'
      - 4559-4564:4559-4564
    restart: always

volumes:
  daemon:
  rss:

networks:
  default:
    name: shore
