#!/bin/sh
set -eux

mkdir -p /var/lib/transmission/downloads
install -d -o transmission -g transmission -m 750 /var/lib/transmission/.config/transmission-daemon/
install -o transmission -g transmission -m 640 /etc/transmission/settings.json /var/lib/transmission/.config/transmission-daemon/settings.json

eval exec gosu "transmission:transmission" "$@"
