#!/bin/sh
set -eux

command -v stat > /dev/null || { echo "Can't find stat, exiting."; exit 1; }
command -v gosu > /dev/null || { echo "Can't find gosu, exiting."; exit 1; }

ln -sf /etc/transmission/settings.json ./settings.json

if [ -d ./Downloads ] && [ "$(id -u)" -eq '0' ]
then
    uid="$(stat ./Downloads -c '%u')"
    gid="$(stat ./Downloads -c '%g')"
    chown "$uid:$gid" ./
    eval exec gosu "$uid:$gid" "$@"
else
    eval exec "$@"
fi
